import "dotenv/config"
import { PrismaClient } from "../src/generated/prisma/client.js"
import { withAccelerate } from "@prisma/extension-accelerate"

const prisma = new PrismaClient({
  accelerateUrl: process.env.DATABASE_URL!,
}).$extends(withAccelerate())

async function seed() {
  await prisma.user.createMany({
    data: [
      { name: "Birgitta Sandström", email: "birgitta.sandstrom@folkhogskola.se", age: 52, isMarried: true, languages: ["Swedish", "English", "German"] },
      { name: "Tobias Henriksson", email: "tobias.henriksson@folkhogskola.se", age: 34, isMarried: false, languages: ["Swedish", "English"] },
      { name: "Amara Diallo", email: "amara.diallo@folkhogskola.se", age: 28, isMarried: false, languages: ["French", "Wolof", "English"] },
      { name: "Rasmus Lindqvist", email: "rasmus.lindqvist@folkhogskola.se", age: 41, isMarried: true, languages: ["Swedish", "English"] },
      { name: "Fatima Al-Hassan", email: "fatima.alhassan@folkhogskola.se", age: 35, isMarried: true, languages: ["Arabic", "English", "French"] },
      { name: "Pontus Ekberg", email: "pontus.ekberg@folkhogskola.se", age: 23, isMarried: false, languages: ["Swedish", "English"] },
      { name: "Yuki Tanaka", email: "yuki.tanaka@folkhogskola.se", age: 29, isMarried: false, languages: ["Japanese", "English"] },
      { name: "Viktor Söderberg", email: "viktor.soderberg@folkhogskola.se", age: 19, isMarried: false, languages: ["Swedish", "English"] },
      { name: "Priya Nair", email: "priya.nair@folkhogskola.se", age: 45, isMarried: true, languages: ["Malayalam", "Hindi", "English"] },
      { name: "Mattias Zettergren", email: "mattias.zettergren@folkhogskola.se", age: 31, isMarried: true, languages: ["Swedish", "English"] },
      { name: "Erik Johansson", email: "erik.johansson@folkhogskola.se", age: 27, isMarried: false, languages: ["Swedish", "English", "Spanish"] },
      { name: "Mei-Ling Chen", email: "meiling.chen@folkhogskola.se", age: 44, isMarried: true, languages: ["Mandarin", "English", "Cantonese"] },
      { name: "Anders Nilsson", email: "anders.nilsson@folkhogskola.se", age: 38, isMarried: true, languages: ["Swedish", "English"] },
      { name: "Kofi Mensah", email: "kofi.mensah@folkhogskola.se", age: 29, isMarried: false, languages: ["Twi", "English", "French"] },
      { name: "Johan Eriksson", email: "johan.eriksson@folkhogskola.se", age: 55, isMarried: true, languages: ["Swedish", "English", "Danish"] },
      { name: "Valentina Russo", email: "valentina.russo@folkhogskola.se", age: 33, isMarried: false, languages: ["Italian", "English", "French"] },
      { name: "Lars Olsson", email: "lars.olsson@folkhogskola.se", age: 48, isMarried: true, languages: ["Swedish", "English"] },
      { name: "Aisha Okonkwo", email: "aisha.okonkwo@folkhogskola.se", age: 22, isMarried: false, languages: ["Igbo", "English", "Yoruba"] },
      { name: "Stefan Lindström", email: "stefan.lindstrom@folkhogskola.se", age: 61, isMarried: true, languages: ["Swedish", "English", "German"] },
      { name: "Nadia Petrov", email: "nadia.petrov@folkhogskola.se", age: 36, isMarried: true, languages: ["Russian", "English", "Ukrainian"] },
      { name: "Mikael Hansson", email: "mikael.hansson@folkhogskola.se", age: 43, isMarried: false, languages: ["Swedish", "English"] },
      { name: "Layla Mahmoud", email: "layla.mahmoud@folkhogskola.se", age: 51, isMarried: true, languages: ["Arabic", "English"] },
      { name: "Peter Månsson", email: "peter.mansson@folkhogskola.se", age: 26, isMarried: false, languages: ["Swedish", "English", "Norwegian"] },
      { name: "Soo-Yeon Park", email: "sooyeon.park@folkhogskola.se", age: 39, isMarried: true, languages: ["Korean", "English", "Japanese"] },
      { name: "Thomas Åberg", email: "thomas.aberg@folkhogskola.se", age: 57, isMarried: true, languages: ["Swedish", "English", "Finnish"] },
      { name: "Camille Dupont", email: "camille.dupont@folkhogskola.se", age: 31, isMarried: false, languages: ["French", "English"] },
      { name: "Nicklas Strand", email: "nicklas.strand@folkhogskola.se", age: 24, isMarried: false, languages: ["Swedish", "English", "German"] },
      { name: "Rohan Sharma", email: "rohan.sharma@folkhogskola.se", age: 46, isMarried: true, languages: ["Hindi", "English", "Punjabi"] },
      { name: "Fredrik Nyström", email: "fredrik.nystrom@folkhogskola.se", age: 35, isMarried: true, languages: ["Swedish", "English"] },
      { name: "Ximena Torres", email: "ximena.torres@folkhogskola.se", age: 20, isMarried: false, languages: ["Spanish", "English", "Portuguese"] },
      { name: "Magnus Hedlund", email: "magnus.hedlund@folkhogskola.se", age: 53, isMarried: true, languages: ["Swedish", "English", "Norwegian"] },
      { name: "Zara Ahmed", email: "zara.ahmed@folkhogskola.se", age: 30, isMarried: false, languages: ["Urdu", "English", "Arabic"] },
      { name: "Patrik Engström", email: "patrik.engstrom@folkhogskola.se", age: 42, isMarried: true, languages: ["Swedish", "English"] },
      { name: "Hanna Wikström", email: "hanna.wikstrom@folkhogskola.se", age: 25, isMarried: false, languages: ["Swedish", "English", "French"] },
      { name: "Ibrahim Traoré", email: "ibrahim.traore@folkhogskola.se", age: 49, isMarried: true, languages: ["French", "Bambara", "English"] },
      { name: "Sara Blomqvist", email: "sara.blomqvist@folkhogskola.se", age: 32, isMarried: false, languages: ["Swedish", "English", "Spanish"] },
      { name: "Oskar Lundgren", email: "oskar.lundgren@folkhogskola.se", age: 18, isMarried: false, languages: ["Swedish", "English"] },
      { name: "Amina Yılmaz", email: "amina.yilmaz@folkhogskola.se", age: 58, isMarried: true, languages: ["Turkish", "English", "German"] },
      { name: "Kristoffer Åkesson", email: "kristoffer.akesson@folkhogskola.se", age: 40, isMarried: true, languages: ["Swedish", "English"] },
      { name: "Chioma Eze", email: "chioma.eze@folkhogskola.se", age: 27, isMarried: false, languages: ["Igbo", "English", "French"] },
      { name: "Marcus Lindberg", email: "marcus.lindberg@folkhogskola.se", age: 21, isMarried: false, languages: ["Swedish", "English", "Danish"] },
      { name: "Olena Kovalenko", email: "olena.kovalenko@folkhogskola.se", age: 56, isMarried: true, languages: ["Ukrainian", "Russian", "English"] },
      { name: "Simon Wallin", email: "simon.wallin@folkhogskola.se", age: 29, isMarried: false, languages: ["Swedish", "English"] },
      { name: "Leila Hosseini", email: "leila.hosseini@folkhogskola.se", age: 38, isMarried: true, languages: ["Farsi", "English", "French"] },
      { name: "Robert Sjöberg", email: "robert.sjoberg@folkhogskola.se", age: 62, isMarried: true, languages: ["Swedish", "English", "German"] },
      { name: "Kwame Asante", email: "kwame.asante@folkhogskola.se", age: 27, isMarried: false, languages: ["Twi", "English"] },
      { name: "Hampus Dahl", email: "hampus.dahl@folkhogskola.se", age: 33, isMarried: false, languages: ["Swedish", "English", "Spanish"] },
      { name: "Anastasia Volkov", email: "anastasia.volkov@folkhogskola.se", age: 50, isMarried: true, languages: ["Russian", "English", "French"] },
      { name: "Niklas Bergman", email: "niklas.bergman@folkhogskola.se", age: 44, isMarried: true, languages: ["Swedish", "English"] },
      { name: "Blessing Osei", email: "blessing.osei@folkhogskola.se", age: 23, isMarried: false, languages: ["Twi", "English", "Hausa"] },
      { name: "Alexander Ström", email: "alexander.strom@folkhogskola.se", age: 36, isMarried: false, languages: ["Swedish", "English", "Finnish"] },
      { name: "Hyun-Ji Kim", email: "hyunji.kim@folkhogskola.se", age: 41, isMarried: true, languages: ["Korean", "English"] },
      { name: "Oscar Hedström", email: "oscar.hedstrom@folkhogskola.se", age: 19, isMarried: false, languages: ["Swedish", "English"] },
      { name: "Sofía Martínez", email: "sofia.martinez@folkhogskola.se", age: 54, isMarried: true, languages: ["Spanish", "English", "Catalan"] },
      { name: "William Norberg", email: "william.norberg@folkhogskola.se", age: 28, isMarried: false, languages: ["Swedish", "English", "Norwegian"] },
      { name: "Nour El-Din", email: "nour.eldin@folkhogskola.se", age: 46, isMarried: true, languages: ["Arabic", "English", "French"] },
      { name: "Felix Lundqvist", email: "felix.lundqvist@folkhogskola.se", age: 22, isMarried: false, languages: ["Swedish", "English"] },
      { name: "Anya Kozlov", email: "anya.kozlov@folkhogskola.se", age: 35, isMarried: true, languages: ["Russian", "English", "Polish"] },
      { name: "Hugo Carlsson", email: "hugo.carlsson@folkhogskola.se", age: 60, isMarried: true, languages: ["Swedish", "English", "German"] },
      { name: "Tariq Hassan", email: "tariq.hassan@folkhogskola.se", age: 24, isMarried: false, languages: ["Somali", "Arabic", "English"] },
      { name: "Liam Johansson", email: "liam.johansson@folkhogskola.se", age: 31, isMarried: false, languages: ["Swedish", "English"] },
      { name: "Adaeze Obi", email: "adaeze.obi@folkhogskola.se", age: 43, isMarried: true, languages: ["Igbo", "English", "Yoruba"] },
      { name: "Elias Magnusson", email: "elias.magnusson@folkhogskola.se", age: 37, isMarried: true, languages: ["Swedish", "English", "Spanish"] },
      { name: "Gabriella Kovács", email: "gabriella.kovacs@folkhogskola.se", age: 26, isMarried: false, languages: ["Hungarian", "English", "German"] },
      { name: "Noah Persson", email: "noah.persson@folkhogskola.se", age: 48, isMarried: true, languages: ["Swedish", "English"] },
      { name: "Mariam Touré", email: "mariam.toure@folkhogskola.se", age: 20, isMarried: false, languages: ["French", "Fulani", "English"] },
      { name: "Lucas Nilsson", email: "lucas.nilsson@folkhogskola.se", age: 55, isMarried: true, languages: ["Swedish", "English", "Danish"] },
      { name: "Dilnoza Yusupova", email: "dilnoza.yusupova@folkhogskola.se", age: 29, isMarried: false, languages: ["Uzbek", "Russian", "English"] },
      { name: "Oliver Olsson", email: "oliver.olsson@folkhogskola.se", age: 39, isMarried: true, languages: ["Swedish", "English"] },
      { name: "Emre Demir", email: "emre.demir@folkhogskola.se", age: 32, isMarried: false, languages: ["Turkish", "English", "German"] },
      { name: "Axel Bergström", email: "axel.bergstrom@folkhogskola.se", age: 57, isMarried: true, languages: ["Swedish", "English", "Norwegian"] },
      { name: "Tsehay Bekele", email: "tsehay.bekele@folkhogskola.se", age: 21, isMarried: false, languages: ["Amharic", "English", "Oromo"] },
      { name: "Vincent Larsson", email: "vincent.larsson@folkhogskola.se", age: 44, isMarried: true, languages: ["Swedish", "English"] },
      { name: "Lucía Fernández", email: "lucia.fernandez@folkhogskola.se", age: 33, isMarried: false, languages: ["Spanish", "English", "French"] },
      { name: "Adrian Holm", email: "adrian.holm@folkhogskola.se", age: 27, isMarried: false, languages: ["Swedish", "English", "Finnish"] },
      { name: "Pham Thi Lan", email: "pham.thilan@folkhogskola.se", age: 51, isMarried: true, languages: ["Vietnamese", "English"] },
      { name: "Kevin Sjögren", email: "kevin.sjogren@folkhogskola.se", age: 36, isMarried: true, languages: ["Swedish", "English", "Danish"] },
      { name: "Ananya Krishnan", email: "ananya.krishnan@folkhogskola.se", age: 25, isMarried: false, languages: ["Tamil", "English", "Hindi"] },
      { name: "Jonathan Lund", email: "jonathan.lund@folkhogskola.se", age: 49, isMarried: true, languages: ["Swedish", "English"] },
      { name: "Marta Wiśniewska", email: "marta.wisniewska@folkhogskola.se", age: 18, isMarried: false, languages: ["Polish", "English", "German"] },
      { name: "Christoffer Björklund", email: "christoffer.bjorklund@folkhogskola.se", age: 42, isMarried: true, languages: ["Swedish", "English", "Spanish"] },
      { name: "Fatou Dieng", email: "fatou.dieng@folkhogskola.se", age: 30, isMarried: false, languages: ["Wolof", "French", "English"] },
      { name: "Samuel Söderström", email: "samuel.soderstrom@folkhogskola.se", age: 53, isMarried: true, languages: ["Swedish", "English"] },
      { name: "Elena Popescu", email: "elena.popescu@folkhogskola.se", age: 22, isMarried: false, languages: ["Romanian", "English", "French"] },
      { name: "Benjamin Wikström", email: "benjamin.wikstrom@folkhogskola.se", age: 46, isMarried: true, languages: ["Swedish", "English", "German"] },
      { name: "Darius Ionescu", email: "darius.ionescu@folkhogskola.se", age: 35, isMarried: true, languages: ["Romanian", "English", "Italian"] },
      { name: "Maximilian Blomqvist", email: "maximilian.blomqvist@folkhogskola.se", age: 28, isMarried: false, languages: ["Swedish", "English"] },
      { name: "Yewande Adeyemi", email: "yewande.adeyemi@folkhogskola.se", age: 40, isMarried: true, languages: ["Yoruba", "English", "French"] },
      { name: "Tim Holmberg", email: "tim.holmberg@folkhogskola.se", age: 19, isMarried: false, languages: ["Swedish", "English", "Danish"] },
      { name: "Bui Thi Thu", email: "bui.thithu@folkhogskola.se", age: 58, isMarried: true, languages: ["Vietnamese", "English", "French"] },
      { name: "Philip Sundqvist", email: "philip.sundqvist@folkhogskola.se", age: 24, isMarried: false, languages: ["Swedish", "English"] },
      { name: "Alinta Watson", email: "alinta.watson@folkhogskola.se", age: 47, isMarried: true, languages: ["English"] },
      { name: "Sebastian Hellström", email: "sebastian.hellstrom@folkhogskola.se", age: 31, isMarried: false, languages: ["Swedish", "English", "Norwegian"] },
      { name: "Özge Çelik", email: "ozge.celik@folkhogskola.se", age: 38, isMarried: true, languages: ["Turkish", "English", "Kurdish"] },
      { name: "Anton Nordin", email: "anton.nordin@folkhogskola.se", age: 62, isMarried: true, languages: ["Swedish", "English"] },
      { name: "Sipho Dlamini", email: "sipho.dlamini@folkhogskola.se", age: 27, isMarried: false, languages: ["Zulu", "English", "Xhosa"] },
      { name: "Gustav Fransson", email: "gustav.fransson@folkhogskola.se", age: 43, isMarried: true, languages: ["Swedish", "English", "German"] },
      { name: "Rut Dahl", email: "rut.dahl@folkhogskola.se", age: 56, isMarried: true, languages: ["Swedish", "English"] },
    ],
  })
}

seed().then(() => prisma.$disconnect())